if __name__ == "__main__":
    print("This is the main entry point for the HFT Agent project.")
    print("However, training and evaluation are typically run via specific scripts.")
    print("\nPlease use the following commands from the project root directory:")
    print("--------------------------------------------------------------------")
    print("To train the agent:")
    print("  python3 -m scripts.train")
    print("")
    print("To evaluate a trained agent:")
    print("  python3 -m scripts.evaluate")
    print("--------------------------------------------------------------------")
    print("\nConfiguration for training and evaluation can be found within these respective scripts.")
    print("Ensure you have installed all dependencies from requirements.txt and have a trained model")
    print("(e.g., trained_models/ppo_actor_critic_hft.pth) for evaluation.")
